var web3;
var address="0x05d29be85f91975fd786e3fd6587db7f78a44e67";

async function connect() {
    await windows.web3.currentProvider.enable();
    web3=new Web3(windows.web3.currentProvider);
}

if (typeof web3 !== "undefine"){
    web3 = new Web3(windows.web3.currentProvider);
}

else{
    web3=new Web3(new web3.Provider.HttpProvider(""));
}

var abi=[
    {
        "inputs":[],
        "stateMutability":"nonpayable",
        "type":"constructor"
    },
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"owner",
                    "type":"address"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"spender",
                    "type":"address"
                },
                {
                    "indexed":false,
                    "internalType":"uint256",
                    "name":"value",
                    "type":"uint256"
                }],
                "name":"Approval",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"previousOwner",
                        "type":"address"
                    },
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"newOwner",
                        "type":"address"
                    }],
                    "name":"OwnershipTransferred",
                    "type":"event"
                },
                {
                    "anonymous":false,
                    "inputs":[
                        {
                            "indexed":false,
                            "internalType":"uint256",
                            "name":"swaped",
                            "type":"uint256"
                        },
                        {
                            "indexed":false,
                            "internalType":"uint256",
                            "name":"recieved",
                            "type":"uint256"
                        }],
                        "name":"Swap",
                        "type":"event"
                    },
                    {
                        "anonymous":false,
                        "inputs":[
                            {
                                "indexed":true,
                                "internalType":"address",
                                "name":"from",
                                "type":"address"
                            },
                            {
                                "indexed":true,
                                "internalType":"address",
                                "name":"to",
                                "type":"address"
                            },
                            {
                                "indexed":false,
                                "internalType":"uint256",
                                "name":"value",
                                "type":"uint256"
                            }],
                            "name":"Transfer",
                            "type":"event"
                        },
                        {
                            "anonymous":false,
                            "inputs":[
                                {
                                    "indexed":false,
                                    "internalType":"string",
                                    "name":"name",
                                    "type":"string"
                                },
                                {
                                    "components":[
                                        {
                                            "internalType":"string",
                                            "name":"name",
                                            "type":"string"
                                        },
                                        {
                                            "internalType":"uint256",
                                            "name":"value",
                                            "type":"uint256"
                                        }],
                                        "indexed":false,
                                        "internalType":"struct InfinityRIZE.Log[3]",
                                        "name":"values",
                                        "type":"tuple[3]"
                                    }],
                                    "name":"UpdatedSettings",
                                    "type":"event"
                                },
                                {
                                    "inputs":[],
                                    "name":"_feeDecimal",
                                    "outputs":[
                                        {
                                            "internalType":"uint256",
                                            "name":"",
                                            "type":"uint256"
                                        }],
                                        "stateMutability":"view",
                                        "type":"function"
                                    },
                                    {
                                        "inputs":[
                                            {
                                                "internalType":"uint256",
                                                "name":"",
                                                "type":"uint256"
                                            }],
                                            "name":"_infinityFee",
                                            "outputs":[
                                                {
                                                    "internalType":"uint256",
                                                    "name":"",
                                                    "type":"uint256"
                                                }],
                                                "stateMutability":"view",
                                                "type":"function"
                                            },
                                            {
                                                "inputs":[
                                                    {
                                                        "internalType":"address",
                                                        "name":"",
                                                        "type":"address"
                                                    }],
                                                    "name":"_isExcludedFromFee",
                                                    "outputs":[
                                                        {
                                                            "internalType":"bool",
                                                            "name":"",
                                                            "type":"bool"
                                                        }],
                                                        "stateMutability":"view",
                                                        "type":"function"
                                                    },
                                                    {
                                                        "inputs":[
                                                            {
                                                                "internalType":"uint256",
                                                                "name":"",
                                                                "type":"uint256"
                                                            }],
                                                            "name":"_rewardsFee",
                                                            "outputs":[
                                                                {
                                                                    "internalType":"uint256",
                                                                    "name":"",
                                                                    "type":"uint256"
                                                                }],
                                                                "stateMutability":"view",
                                                                "type":"function"
                                                            },
                                                            {
                                                                "inputs":[
                                                                    {
                                                                        "internalType":"uint256",
                                                                        "name":"",
                                                                        "type":"uint256"
                                                                    }],
                                                                    "name":"_transferFee",
                                                                    "outputs":[
                                                                        {
                                                                            "internalType":"uint256",
                                                                            "name":"",
                                                                            "type":"uint256"
                                                                        }],
                                                                        "stateMutability":"view",
                                                                        "type":"function"
                                                                    },
                                                                    {
                                                                        "inputs":[
                                                                            {
                                                                                "internalType":"address",
                                                                                "name":"owner",
                                                                                "type":"address"
                                                                            },
                                                                            {
                                                                                "internalType":"address",
                                                                                "name":"spender",
                                                                                "type":"address"
                                                                            }],
                                                                            "name":"allowance",
                                                                            "outputs":[
                                                                                {
                                                                                    "internalType":"uint256",
                                                                                    "name":"","type":"uint256"
                                                                                }],
                                                                                "stateMutability":"view",
                                                                                "type":"function"
                                                                            },
                                                                            {
                                                                                "inputs":[
                                                                                    {
                                                                                        "internalType":"address",
                                                                                        "name":"spender",
                                                                                        "type":"address"
                                                                                    },
                                                                                    {
                                                                                        "internalType":"uint256",
                                                                                        "name":"amount",
                                                                                        "type":"uint256"
                                                                                    }],
                                                                                    "name":"approve",
                                                                                    "outputs":[
                                                                                        {
                                                                                            "internalType":"bool",
                                                                                            "name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"account","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"deadAddr","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"decimals","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"spender","type":"address"},{"internalType":"uint256","name":"subtractedValue","type":"uint256"}],"name":"decreaseAllowance","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"account","type":"address"}],"name":"excludeFromReward","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"getStuckBNB","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"}],"name":"getStuckToken","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"account","type":"address"}],"name":"includeInReward","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"spender","type":"address"},{"internalType":"uint256","name":"addedValue","type":"uint256"}],"name":"increaseAllowance","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"infinityVault","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"account","type":"address"}],"name":"isExcludedFromReward","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"isFeeActive","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"maxTxAmount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"minTokensBeforeSwap","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"name","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"networkTreasury","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"pair","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"tokenAmount","type":"uint256"}],"name":"reflectionFromToken","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"rewardsVault","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"router","outputs":[{"internalType":"contract IUniswapV2Router02","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"account","type":"address"},{"internalType":"bool","name":"value","type":"bool"}],"name":"setExcludeFromFee","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bool","name":"value","type":"bool"}],"name":"setFeeActive","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"buy","type":"uint256"},{"internalType":"uint256","name":"sell","type":"uint256"},{"internalType":"uint256","name":"p2p","type":"uint256"}],"name":"setInfinityFee","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_address","type":"address"}],"name":"setInfinityVault","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_txNumerator","type":"uint256"},{"internalType":"uint256","name":"_divisor","type":"uint256"}],"name":"setMaxTxAmount","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_amount","type":"uint256"}],"name":"setMinTokensBeforeSwap","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_address","type":"address"}],"name":"setNetworkTreasury","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_pair","type":"address"},{"internalType":"contract IUniswapV2Router02","name":"_router","type":"address"}],"name":"setPairRouterRewardToken","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"buy","type":"uint256"},{"internalType":"uint256","name":"sell","type":"uint256"},{"internalType":"uint256","name":"p2p","type":"uint256"}],"name":"setRewardsFee","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_address","type":"address"}],"name":"setRewardsVault","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bool","name":"enabled","type":"bool"}],"name":"setSwapEnabled","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"buy","type":"uint256"},{"internalType":"uint256","name":"sell","type":"uint256"},{"internalType":"uint256","name":"p2p","type":"uint256"}],"name":"setTransferFee","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"swapEnabled","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"symbol","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"reflectionAmount","type":"uint256"}],"name":"tokenFromReflection","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"totalSupply","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"recipient","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"transfer","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"sender","type":"address"},{"internalType":"address","name":"recipient","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"transferFrom","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"stateMutability":"payable","type":"receive"}];
var contract=new web3.eth.contract(abi,address);